services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - auth-service
      - restaurant-service

  auth-service:
    build: ./services/auth
    container_name: auth-service
    volumes:
      - ./services/auth:/app
      - node_modules_auth:/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

  restaurant-service:
    build: ./services/restaurants
    container_name: restaurant-service
    volumes:
      - ./services/restaurants:/app
      - node_modules_restaurants:/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:
  node_modules_auth:
  node_modules_restaurants:

networks:
  app-network:
    driver: bridge